### ISSUE TITLE
[JOSS Review] Add `jaxlib` to requirements

### ISSUE THREAD

**Issue by 1313e** [mpi4jax/mpi4jax#101]
This issue is part of the JOSS Review in openjournals/joss-reviews#3419.

`mpi4jax` requires `jax` in order to function, which is very logical.
However, `jax` requires `jaxlib` to function properly.
Given that, for some reason, `jax` does not automatically install `jaxlib`, either `jax` or `mpi4jax` must add this requirement to the requirements list.
Otherwise `mpi4jax` cannot be installed properly using a single install command.

**Comment by dionhaefner** [comment]
This is by design. There are different versions of jaxlib for CPU and GPU, and I guess the JAX people want users to make a conscious choice of which one to use. We don't want to interfere with that and found it best to stick to what JAX is doing. Given that `mpi4jax` users are probably *already* active JAX users, we don't think this is a huge problem in practice. Let us know if you thought that isn't documented properly (I think we mention installing jaxlib in the docs). 

BTW, according to the official JAX instructions they now *do* include jaxlib with `pip install jax`: https://github.com/google/jax/#installation

**Comment by PhilipVinc** [comment]
(It’s hidden behind “pip install jax[cpu/tpu/cudaXYZ]”).

Il 20 lug 2021, 19:06 +0200, Dion Häfner ***@***.***>, ha scritto:

**Comment by 1313e** [comment]
> BTW, according to the official JAX instructions they now _do_ include jaxlib with `pip install jax`: https://github.com/google/jax/#installation

I installed `jax` yesterday and that did not install `jaxlib` automatically.

Anyway, simply mentioning that `jax` and `jaxlib` must be installed manually before installing `mpi4jax` in the README would be fine.
I am saying the README here, as many users only look at the README and not at the docs for installation instructions.

PS: `mpi4jax` does install `jax` automatically, as it has it as a requirement, but not `jaxlib`.
If I am going to be honest, it might actually be better to remove `jax` as the requirement, to force users to install `jax` (and thus `jaxlib`) themselves properly.
Because `jax` is currently automatically taken care of, it feels weird that `jaxlib` is not, regardless of what reasons Google has for not including it.

**Comment by dionhaefner** [comment]
I agree that the current state of installing jaxlib manually is awkward, but I really don't see a better solution. IMO the error when running without jaxlib is obvious enough that this shouldn't be a major obstacles for new users (which we assume to mostly be JAX users anyway).

I've added a section to the README, feel free to reopen if you feel that this is still an issue and we'll work on a better solution.

**Comment by 1313e** [comment]
It is good now. :)
It is simply to take out any confusion with beginners.
Should always try to make it as easy as possible for them to get started, and leaving very little up for interpretation.
