### ISSUE TITLE
Colab Example

### ISSUE THREAD

**Issue by pharringtonp19** [mpi4jax/mpi4jax#104]
Would it be possible to create a toy colab example with TPUs? I am having a hard time getting the installation correct.

**Comment by dionhaefner** [comment]
Hey, we've never tried `mpi4jax` with TPUs. Could you give some context on this? What are you actually trying to do?

**Comment by PhilipVinc** [comment]
The MPI workflow does not lend itself to running on Colab: you need to run the same script/notebook on several different machines/nodes/processes/gpus. normally a notebook cell is run only on one process instead...

**Comment by PhilipVinc** [comment]
Moreover, mpi4jax does not work on TPUs at the moment, and I fear it never will.
Google should first expose some API to directly access the memory on TPUs, and then MPI should be adapted to support them.
I'd love this to happen, but...

I think it's more likely that XLA will build into the language better distributed primitives?

Maybe @mattjj could tell us if there's anything in the pipeline..

**Comment by dionhaefner** [comment]
While I agree with most of this I'm not 100% sure that it's not possible to use MPI on TPUs. As of a couple of months ago, you can now SSH into the TPU host VM which is basically just a beefy Linux machine. So it should be possible to use MPI / `mpi4jax` on the host VMs CPUs. But I don't have enough experience to say how and if that is possible.

**Comment by PhilipVinc** [comment]
Interesting. I guess it's linked with the libtpu announcement..?

Anyhow I guess that we would have to implement some workaround like we have for non coda-enabled MPI: copy the buffers to host, then run mpi operation, then back to device.
That means using `libtpu`, linking against it to use something like `device_buffer_to_host` copy.

Though since you have... what? 32 tpus per host I think that's not going to work super-well...

**Comment by pharringtonp19** [comment]
@dionhaefner I know very little about any of this stuff, but I enjoy experimenting/playing around with libraries related to jax. I thought if there was a nice colab example, I could get a better sense of whether I could use this library in my current work -- where I am trying to maximize the number of feed-forward neural networks I can train in parallel!

**Comment by dionhaefner** [comment]
I see. MPI is not really about running multiple identical things in parallel. Instead, you would use many devices to solve 1 big problem. For example, you might want to use dozens of GPUs spread across a cluster to collectively train the same network.

So in this case I agree that this is not really Colab material, since MPI only makes sense if you have more than 1 device.

If all you want to do is train multiple networks in parallel, I suggest you use something like `concurrent.futures` to create a process pool.
