### ISSUE TITLE
Automated token management via decorator?

### ISSUE THREAD

**Issue by dionhaefner** [mpi4jax/mpi4jax#107]
In Veros, we have a decorator that does automated token management. This is roughly how it works:

```python
__current_token = None

def get_token():
    return __current_token

def set_token(new_token):
    global __current_token
    __current_token = new_token

def token_context(jit=False):
    def newfunc(func):
        def wrapped(*args, **kwargs, token=None):
            set_token(token)
            res = func(*args, **kwargs)
            token = get_token()
            # returning the token ensures that Tracers are propagated 
            # correctly through nested JITs
            return res, token

         if jit:
             wrapped = jax.jit(wrapped)

         def wrapped_2(*args, **kwargs):
             # peel off token argument from wrapped
             token = get_token()
             res, token = wrapped(*args, **kwargs, token=token)
             set_token(token)
             return res

         return wrapped_2

    return newfunc

def auto_allreduce(*args, **kwargs):
    token = get_token()
    res, token = mpi4jax.allreduce(*args, **kwargs, token=token)
    set_token(token)
    return res    
```

Then you can use it like this:

```python
@token_context(jit=True)  # use this instead of jax.jit
def myfunc(arr):
    res = auto_allreduce(arr)
    return res

@token_context(jit=True)
def myfunc_2(arr):
    # no problem with tokens
    res = auto_allreduce(arr)
    res = myfunc()
    res = auto_allreduce(arr)
    return res
```

This way, there is no need to carry around a token object several layers deep into nested JITs, and there is no way to mess up token order.

Disadvantages:
- Doesn't work in `fori_loop` and friends (still need manual token management for now, but maybe it could be done, I haven't tried very hard)
- Must use this decorator instead of `jax.jit`

Is this something we should port into `mpi4jax`?

**Comment by Thenerdstation** [comment]
I think this is a good idea. Having a systemic way to avoid the footgun of either missing or incorrectly using the communication tokens I see as a very net positive. However, instead of just using a context manager that's fragile to jit, I think it would be a good idea to map it to a transform instead, similar to how `vmap` functions.

The usage of it in this case would look something like this

```python
def func(A):
  return mpi4jax.auto.all_reduce(A)

# The `token` argument default to None.
tokened_func = mpi4jax.auto_tokens(token)(func)
results, new_token = tokened_func(my, func, args)
```

In this case, `tokened_func` gets transformed to a function that is equivalent to:
```python
def tokened_func(token, A):
    result, new_token =  mpi4jax.all_reduce(A, token)
    return result, new_token
```
Because of this, you could use `jit` as you normally would in any other context.

```python
@jax.jit
def f(A):
  # No token passed defaults to creating a brand new token.
  tokened_func = mpi4jax.auto_tokens()(func)
  results, _ = tokened_func(my, func, args)
  return results
```

The transform could also add the support for a `fori_loop`. The mapping would just become
```python
results = fori_loop(f, [my, func, args]) 
=>
results, new_token = fori_loop(tokenize(token)(f), [token, my, func, args])
```

Can I actually take the lead on this? I'm looking to contribute to this project and I think this would be a nice first contribution.

**Comment by PhilipVinc** [comment]
Hey @Thenerdstation , thanks for chiming in!

I like the idea. It's more functional, therefore more consistent with jax, and does not hide state which might play badly with tracing.

And solves the issue of the fori_loop.

One nitpick I have, however, is that I'd make the `auto_tokenize` function take and return a transformed function in order to be more consistent with things like jax.jit and vmap. 

I'n still unsure on how to make it work, however: if it's only a functional transformation, it should not take a token as input , instead it might add a keyword argument to the wrapped function, say `token=`, which could even be autogenerated.
The transformed function would then return a tuple of the original result and a token.

I'm still not 100% convinced of this design I am proposing, but I'd like to make it consistent with more standard api.

Anyhow, I'd be very happy if you decided to contribute this to `mpi4jax`.
Maybe it might save some iterations if we agree on the high level api before hand, but otherwise, it would be a welcome addition.

(I think @dionhaefner will agree with me?)

**Comment by Thenerdstation** [comment]
I personally would prefer to avoiding adding a `token=` to the generated function, as that adds an additional footgun of a possibly colliding with an already existing `token` keyword argument. Given the current API example would already allow a user to implement this themselves fairly easily if they wanted to.

```
def add_token_arg(f):
  return lambda token, *args, **kwargs: mpi4jax.auto_tokenize(token)(f)

tokened_f = add_token_arg(f)
result = tokened_f(token=some_token, other_arg=my_var)
```

I do agree that `auto_tokenize(token)(f)` is a little clunky. Maybe instead we do `auto_tokenize(f, token=...)`? In that case, if token is `None`, we default to creating a brand new token.

**Comment by Thenerdstation** [comment]
So, here is my full API proposal
1) Add a `mpi4jax.auto` module. This remaps all or most of the available tokenizable functions to new functions that don't accept a token, and instead are required to be transformed.
2) Add `mpi4jax.auto_tokenize(f, token=None)` that returns a new function where all of the `mpi4jax.auto` methods are replaced with standard methods that have their tokens automatically managed. 
3) If any `mpi4jax.auto` primitive is executed without being transformed, raise an error.

**Comment by PhilipVinc** [comment]
I was thinking that it would be great to be able to nest this decorator together with jax.jit, vmap or others.

In that case the token must be an argument and it can't be a 'trace time' constant.

I was thinking along the lines of 
```python
@jax.jit
@mpi4jax.auto.tokenize(return_token=False)
Def fun(x,y...):
  ...

```

That way it becomes almost transparent...

But the issue you raise is indeed valid.

**Comment by Thenerdstation** [comment]
I think we are on the same page. Other than the `return_token` argument you add (which I agree we should add), the nesting you suggest would still work. In the case you have above, the `token` argument in `auto_tokenize` would be `None`, so we would generate a new token automatically before the `jit` kicks in.

**Comment by Thenerdstation** [comment]
Actually, upon further thinking, we don't even need the `auto` sub module at all either. The transform could simply replace all instances of the standard API where `token=None`.

**Comment by PhilipVinc** [comment]
> 1 Add a mpi4jax.auto module. This remaps all or most of the available tokenizable functions to new functions that don't accept a token, and instead are required to be transformed.

I agree with this. It's true that we might replace everywhere we have a token=None but that might be a bit more brittle

> Add mpi4jax.auto_tokenize(f, token=None) that returns a new function where all of the mpi4jax.auto methods are replaced with standard methods that have their tokens automatically managed.

My problem with that approach is the following: if `auto_tokenize` is to be a function transformation it cannot take a token, which in general is a concrete value. The token must be passed at execution time.

If we decide that `auto_tokenize` is not a function transformation, then i'm fine with that.
